leftnav:
- identifier: 9ca839c1-15e4-a71b-90bc-569ef2ddba48
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: aaf2e239-79d6-feb6-465d-4294f3221043
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: b00e390c-781e-1aa0-5a7a-4ba632ea1b28
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1f2a7f5a-2e2d-d2a9-b4dd-7564536bf476
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: aa2f0cdf-02c5-54d8-00f2-a452eba20004
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 50
